services:
  oapi-codegen:
    build: .
    container_name: oapi-codegen
    volumes:
      - ../generated:/generated
      - .:/tools
      - ../../oapi_gen:/oapi_gen
  
  swagger-cli:
    build:
      context: ./swagger-cli
    container_name: swagger-cli
    volumes:
      - ../components:/components
      - ../generated:/generated
      - .:/tools
  
  redocly-cli:
    build:
      context: ./redocly
    container_name: redocly-cli
    volumes:
      - ../components:/components
      - ../generated:/generated
      - .:/tools
    environment:
      - REDOCLY_TELEMETRY=off
