openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
paths:
  /users/{userId}:
    get:
      summary: Get user information
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
