openapi: 3.0.3

info:
  title: "OpenAPI template"
  version: "1.0.0"

servers:
  - url: https://api.example.com/api/v1
    description: production
  - url: https://{environment}.api.example.com/api/v1
    variables:
      environment:
        default: dev
        enum:
          - dev
          - staging
    description: develop
  - url: "{protocol}://{host}:{port}/api/v1"
    description: local
    variables:
      protocol:
        enum:
          - http
          - https
        default: http
      host:
        default: localhost
      port:
        enum:
          - '8080'
        default: '8080'

tags:
  - name: Users
  - name: Todos

paths:
  /todos:
    $ref: './paths/todos/todos.yaml'
  /todos/{todoId}:
    $ref: './paths/todos/todo.yaml'

components:
  schemas:
    $ref: './components/schemas/index.yaml'
  requestBodies:
    $ref: './components/requestBodies/index.yaml'
  responses:
    $ref: './components/responses/index.yaml'
  parameters:
    $ref: './components/parameters/index.yaml'