// Package oapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package oapi

// UserModel User model
type UserModel struct {
	Address *struct {
		City    *string `json:"city,omitempty"`
		Street  *string `json:"street,omitempty"`
		Suite   *string `json:"suite,omitempty"`
		Zipcode *string `json:"zipcode,omitempty"`
	} `json:"address,omitempty"`
	Email string  `json:"email"`
	Id    *string `json:"id,omitempty"`
	Name  string  `json:"name"`
}

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse struct {
	// Users ユーザー一覧
	Users *[]UserModel `json:"users,omitempty"`
}

// PostUsersResponse defines model for PostUsersResponse.
type PostUsersResponse struct {
	// Users User model
	Users *UserModel `json:"users,omitempty"`
}

// PostUserRequestBody defines model for PostUserRequestBody.
type PostUserRequestBody struct {
	// User User model
	User *UserModel `json:"user,omitempty"`
}

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	Page *int `form:"page,omitempty" json:"page,omitempty"`
}

// PostUsersJSONBody defines parameters for PostUsers.
type PostUsersJSONBody struct {
	// User User model
	User *UserModel `json:"user,omitempty"`
}

// PostUsersJSONRequestBody defines body for PostUsers for application/json ContentType.
type PostUsersJSONRequestBody PostUsersJSONBody
